# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np 

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.show_config()

{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "14.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.2",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "14.2.1",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.29",
      "detection method": "pkgconfig",
      "include directory": "/opt/_internal/cpython-3.13.3/lib/python3.13/site-packages/scipy_openblas64/include",
      "lib directory": "/opt/_internal/cpython-3.13.3/lib/python3.13/site

/home/tab/Desktop/Code/Repositories/Me/numpy-100/.venv/lib/python3.13/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [38]:
arr3 = np.zeros(10)
print(arr3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [40]:
arr4 = arr3.copy()
arr4.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [18]:
np.info("add")

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via t

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [41]:
arr6 = np.zeros(10)
arr6[4] = 1
print(arr6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [42]:
arr7 = np.arange(40) + 10
print(arr7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [43]:
arr8 = arr7[::-1]
print(arr8)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [46]:
arr9 = np.arange(9).reshape((3,3))
print(arr9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [48]:
arr10 = np.array([1,2,0,0,4,0])
np.where(arr10)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [51]:
arr11 = np.identity(3)
print(arr11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [56]:
arr12 = np.random.rand(3,3,3)
print(arr12)

[[[0.8248417  0.95503307 0.91332693]
  [0.39504361 0.48060106 0.69759413]
  [0.59917241 0.41721063 0.21642846]]

 [[0.27824173 0.71134612 0.19072446]
  [0.35891626 0.21354738 0.69502002]
  [0.75153088 0.65654966 0.61299745]]

 [[0.42577228 0.13246544 0.69367693]
  [0.24466229 0.01123154 0.67590825]
  [0.03748934 0.49888734 0.92635944]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [60]:
arr13 = np.random.random((10, 10))
print(arr13.flatten().min())
print(arr13.flatten().max())

0.014486713559349051
0.9941920390595335


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [61]:
arr14 = np.random.random(30)
print(arr14.mean())

0.5170811943957199


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [80]:
n = 5
arr15 = np.zeros((n,n))
arr15[0,:] = 1
arr15[n-1,:] = 1
arr15[:,0] = 1
arr15[:,n-1] = 1
print(arr15)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [82]:
arr16 = np.ones((n,n))
arr16 = np.pad(arr16, pad_width=1, mode='constant', constant_values=0)
print(arr16)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [85]:
print(0 * np.nan) # i think nan (correct)
print(np.nan == np.nan) # i think true (false)
print(np.inf > np.nan) # i think true (false)
print(np.nan - np.nan) # i tink nan (correct)
print(np.nan in set([np.nan])) # i think true (true)
print(0.3 == 3 * 0.1) # i think true (false)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [87]:
arr18 = np.diag(np.arange(1,5), k=-1)
print(arr18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [94]:
arr19 = np.fromfunction(lambda i,j: i+j%2==1, (n,n), dtype=np.int32)
print(arr19)

[[False  True False  True False]
 [ True False  True False  True]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [107]:
ds, d = (6,7,8), [None]*3
for i in range(len(d)):
    d[i], new_d = np.zeros(ds), ([1]*3)
    new_d[i] = ds[i]
    d[i] += np.arange(ds[i]).reshape((new_d))
    d[i] = d[i].flatten()
    print(f'{int(d[i][99])}', end="," if i+1 != len(d) else "\n")

# answer(20)
print(np.unravel_index(99,(6,7,8)))


1,5,3
(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [109]:
arr21 = np.tile([[1,0],[0,1]], (4,4))
print(arr21)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [119]:
arr22 = np.random.random((5,5)) * 20
arr22 = (arr22 - arr22.mean()) / arr22.std()
print(arr22, arr22.mean(), arr22.std())

[[ 1.15514453  1.32857823 -1.65682221  0.44930442 -0.70670284]
 [-1.14305405  0.41750168 -1.04135069  0.33176786 -1.03677003]
 [ 0.42307016 -0.65200139 -0.97160599  1.90563827 -0.41889542]
 [-1.12878861  0.86798192 -0.10682484  0.01569595 -1.69166662]
 [ 1.26579881  1.22720668  0.94173491  0.57482705 -0.34976777]] 1.887379141862766e-16 1.0


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [123]:
ub = np.ubyte
dt = np.dtype([('R', ub), ('G', ub), ('B', ub), ('A', ub)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [126]:
arr24_1, arr24_2 = np.random.random((5,3)), np.random.random((3,2))
print(arr24_1 @ arr24_2)
print(np.matmul(arr24_1, arr24_2))

[[0.36842025 0.7220086 ]
 [1.36061265 0.90999561]
 [1.03579821 1.28638711]
 [0.80951446 1.07652399]
 [1.140125   0.87842345]]
[[0.36842025 0.7220086 ]
 [1.36061265 0.90999561]
 [1.03579821 1.28638711]
 [0.80951446 1.07652399]
 [1.140125   0.87842345]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [139]:
arr25 = np.random.random(10) * 10
print(arr25)
arr25[(arr25 >= 3) & (arr25 <= 8)] = 0
print(arr25)


[8.14312    8.59670825 1.53300445 3.01049725 6.14558722 0.05230042
 4.15279331 6.52792573 7.17516027 8.46935797]
[8.14312    8.59670825 1.53300445 0.         0.         0.05230042
 0.         0.         0.         8.46935797]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [141]:
#i think array it self
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
#funny!

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [150]:
# i think 2 << Z >> 2 & 1j*Z and  Z/1/1
import numpy as np 

Z = np.random.random(3)
print(Z**Z) # doable
# print(2 << Z >> 2) #undoable
print(print(Z <- Z)) #doable, bastard :)
print(1j*Z) #doable
print(Z/1/1) #doable
# print(Z<Z>Z) #undoable

[0.69469008 0.71042812 0.84058426]
[False False False]
None
[0.+0.31769644j 0.+0.23855759j 0.+0.80622076j]
[0.31769644 0.23855759 0.80622076]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [154]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int), np.array([np.nan]).astype(int).astype(float))

nan
0
[-9223372036854775808] [-9.22337204e+18]


/tmp/ipykernel_110130/3452437832.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_110130/3452437832.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/tmp/ipykernel_110130/3452437832.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int), np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [157]:
arr29 = np.random.random((3,3)) * 10 - 5
print(arr29)
m1 = arr29 < 0
arr29[m1] *= -1 
arr29 = np.ceil(arr29)
arr29[m1] *= -1
print(arr29)



[[-2.26744251  3.23188806  4.7028375 ]
 [ 2.70523823  0.15329283  1.74064972]
 [ 3.19078954 -4.82477965  3.21242502]]
[[-3.  4.  5.]
 [ 3.  1.  2.]
 [ 4. -5.  4.]]
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [159]:
arr30_1 = np.array([1,2,3])
arr30_2 = np.array([1,4,5])
print(np.intersect1d(arr30_1, arr30_2))

[1]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [166]:
np.seterr(all='warn')

{'divide': 'warn', 'over': 'warn', 'under': 'warn', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [167]:
np.sqrt(-1) == np.emath.sqrt(-1)
print(np.sqrt(-1), np.emath.sqrt(-1))

nan 1j


/tmp/ipykernel_110130/113881354.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)
/tmp/ipykernel_110130/113881354.py:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1), np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [169]:
today = np.datetime64('TODAY')
yesterday, tomorrow = today - np.timedelta64(1), today + np.timedelta64(1)
print(yesterday, today, tomorrow)

2025-06-25 2025-06-26 2025-06-27


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [185]:
date = np.datetime64('2016-07-01')
dates = []
while date.item().month == 7:
    dates.append(date)
    date = date + np.timedelta64(1, 'D')
print(dates)

# answer(34)
# Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')


[np.datetime64('2016-07-01'), np.datetime64('2016-07-02'), np.datetime64('2016-07-03'), np.datetime64('2016-07-04'), np.datetime64('2016-07-05'), np.datetime64('2016-07-06'), np.datetime64('2016-07-07'), np.datetime64('2016-07-08'), np.datetime64('2016-07-09'), np.datetime64('2016-07-10'), np.datetime64('2016-07-11'), np.datetime64('2016-07-12'), np.datetime64('2016-07-13'), np.datetime64('2016-07-14'), np.datetime64('2016-07-15'), np.datetime64('2016-07-16'), np.datetime64('2016-07-17'), np.datetime64('2016-07-18'), np.datetime64('2016-07-19'), np.datetime64('2016-07-20'), np.datetime64('2016-07-21'), np.datetime64('2016-07-22'), np.datetime64('2016-07-23'), np.datetime64('2016-07-24'), np.datetime64('2016-07-25'), np.datetime64('2016-07-26'), np.datetime64('2016-07-27'), np.datetime64('2016-07-28'), np.datetime64('2016-07-29'), np.datetime64('2016-07-30'), np.datetime64('2016-07-31')]
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [187]:
A, B = np.random.random((3,3)), np.random.random((3,3))
np.add(A,B, out=B)
np.multiply(A, -1/2, out=A)
np.matmul(A, B, out=A)

array([[-0.76427706, -0.96777542, -1.00567272],
       [-0.78901281, -1.05366277, -1.35667085],
       [-0.44121993, -0.59443535, -0.83416312]])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [200]:
arr36 = np.random.random(5) * 10
print(arr36)
print(np.floor(arr36))
print(arr36 - arr36%1)
print(arr36.astype(int))
print(arr36 // 1) #wow! I'm unstoppable d:



[5.70928242 3.58719366 0.1480243  9.42057415 9.50691979]
[5. 3. 0. 9. 9.]
[5. 3. 0. 9. 9.]
[5 3 0 9 9]
[5. 3. 0. 9. 9.]
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [204]:
arr37 = np.zeros((5,5)) + np.arange(5)
print(arr37)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [209]:
def gen():
    for i in range(10):
        yield i
arr38 = np.fromiter(gen(), dtype=int, count=-1)
print(arr38)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [215]:
arr39 = np.arange(0, 1, 1/12)[1:-1]
print(arr39, len(arr39))
#answer(39)
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333] 10
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [217]:
arr40 = np.random.random(10)
print(arr40)
arr40.sort()
print(arr40)

[0.27042312 0.80741566 0.91874212 0.51801968 0.54435015 0.90830089
 0.85166062 0.99864128 0.34373811 0.22895079]
[0.22895079 0.27042312 0.34373811 0.51801968 0.54435015 0.80741566
 0.85166062 0.90830089 0.91874212 0.99864128]
Z = np.random.random(10)
Z.sort()
print(Z)


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [222]:
arr41 = np.arange(100)
print(np.add.reduce(arr41))



# compare time
from timeit import Timer

timer_reduce = Timer(lambda: np.add.reduce(arr41))
timer_sum = Timer(lambda: np.sum(arr41))

print(f'execution time for add.reduce: {timer_reduce.timeit(number=1000)}')
print(f'execution time for np.sum: {timer_sum.timeit(number=1000)}')


4950
execution time for add.reduce: 0.002987226005643606
execution time for np.sum: 0.007476935992599465


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [225]:
arr42_1 = np.random.random(10)
arr42_2 = np.random.random(10)
print(np.equal(arr42_1, arr42_2).all())

False
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


#### 43. Make an array immutable (read-only) (★★☆)

In [226]:
arr43 = np.array(list(range(10)))
arr43.flags.writeable = False 
arr43[2] = 3

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [232]:
arr44 = np.random.random((10, 2))
x, y = arr44[:,0], arr44[:,1]

r = np.sqrt(np.pow(x, 2) + np.pow(y, 2)).reshape((-1,1))
teta = np.arctan2(y,x).reshape((-1,1))
answer44 = np.hstack((r, teta))
print(answer44)

[[0.42474104 1.00696993]
 [0.94386274 0.20055445]
 [0.38277111 1.24964288]
 [1.06417372 0.77953612]
 [0.44672921 0.4281511 ]
 [0.96069643 1.44629069]
 [0.98681499 1.32238874]
 [0.9987177  0.4469387 ]
 [0.27453927 0.08700476]
 [0.61906835 0.80229335]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [236]:
arr45 = np.random.random(10)
print(arr45)
arr45[np.argmax(arr45)] = 0
print(arr45)

[0.656213   0.67466082 0.88479538 0.24983658 0.09176852 0.64050749
 0.93934632 0.99924417 0.9507586  0.89597279]
[0.656213   0.67466082 0.88479538 0.24983658 0.09176852 0.64050749
 0.93934632 0.         0.9507586  0.89597279]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
xy_type = np.dtype([('x', float), ('y', float)])
arr46 = np.zeros((10, 10), dtype=xy_type)
arr46['x'], arr46['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [249]:
x = np.array(list(range(5)))
y = np.array(list(range(5)))

arr47 = np.zeros((len(x), len(y)))
for i in range(len(x)):
    for j in range(len(y)):
        arr47[i,j] = 1/(x[i] - y[j])


/tmp/ipykernel_110130/312308729.py:7: RuntimeWarning: divide by zero encountered in scalar divide
  arr47[i,j] = 1/(x[i] - y[j])


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [253]:
print(np.iinfo(np.int32).min)
print(np.iinfo(np.int32).max)


-2147483648
2147483647


#### 49. How to print all the values of an array? (★★☆)

In [263]:
arr49 = np.random.random((10, 10))
print(arr49)

[[0.78949773 0.09442097 0.19035176 0.47233109 0.6750333  0.78709509
  0.41480653 0.39562328 0.97006553 0.31341684]
 [0.17123118 0.20249068 0.47803717 0.84725058 0.1651884  0.48250269
  0.6909625  0.37686717 0.90630453 0.06838414]
 [0.48109689 0.95200533 0.91331233 0.94375892 0.19270318 0.18457535
  0.46963678 0.48904536 0.11028654 0.12378427]
 [0.4143185  0.01503331 0.04424419 0.43381799 0.93954726 0.77961152
  0.06168566 0.14528692 0.21886605 0.64611446]
 [0.31894148 0.56903834 0.69074654 0.05510906 0.59720345 0.87432832
  0.32871045 0.79550323 0.64712855 0.10788582]
 [0.47248469 0.03857187 0.59715932 0.22913856 0.77540065 0.52556928
  0.81219646 0.63158644 0.82020951 0.64925651]
 [0.90313283 0.80451654 0.2629036  0.43329723 0.53454391 0.57169614
  0.89336133 0.98051893 0.27582746 0.53238388]
 [0.94796323 0.35543617 0.37136858 0.4697139  0.97827276 0.69230913
  0.69966237 0.47761811 0.3068783  0.01395928]
 [0.4427511  0.12346524 0.62472554 0.89516288 0.1441199  0.09256312
  0.22416121

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [258]:
arr50 = np.random.random(10) * 10 
v = 4
print(arr50)
print(arr50[np.argmin(np.abs(arr50-v))])

[6.98651033 5.0136059  4.68855151 4.98585801 3.54463135 4.02102739
 1.66164231 8.97311073 1.60713583 5.50060948]
4.021027388998979


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [292]:
position_type = np.dtype([('X', float), ('Y', int)])
color_type = np.dtype([('R', int), ('G', float),('B', int)])
pctype = np.dtype([('P', position_type), ('C', color_type)])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [387]:
arr52 = np.random.random((10, 2))*10
x, y = arr52[:,0], arr52[:,1]
x_, y_ = np.subtract.outer(x, x) ** 2, np.subtract.outer(y, y) ** 2
ans = np.sqrt(x_ + y_)

#answer(52)
import spicy
D = spicy.spatial.distance.cdist(arr52,arr52)

print(np.allclose(ans, np.array(D)))

True


#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [315]:
arr53 = (np.random.random(10)*10).astype(np.float32)
print(arr53)
tmp = arr53.view(np.int32)
tmp[:] = arr53
print(tmp)

[5.613684  4.7973714 7.910587  8.952545  1.3797135 7.2418556 7.381264
 4.1471    8.924573  6.529097 ]
[5 4 7 8 1 7 7 4 8 6]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [323]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11''')
arr54 = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(arr54)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [328]:
arr55 = np.random.random((3,3))*10 
for i,v in np.ndenumerate(arr55):
    print(i, v)

(0, 0) 6.83606950544883
(0, 1) 5.592619733987335
(0, 2) 2.918617013036797
(1, 0) 2.8462740019803725
(1, 1) 1.5508581362160023
(1, 2) 5.031578807826843
(2, 0) 8.050323002361127
(2, 1) 3.3186507580400404
(2, 2) 9.509407367426878


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [416]:
sigma = 1
n = 3
x = np.linspace(-5, 5, n)
y = np.linspace(-5, 5, n)
X, Y = np.meshgrid(x, y)
arr56 = np.exp(-(X**2 + Y**2) / (2 * sigma**2))

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [342]:
n, m = 3, 4
arr57 = np.zeros((n,m))
p = np.array([1,2,3])
y, x = np.meshgrid(np.arange(m), np.arange(n))
print(x, '\n', y)
flatten_indices = np.random.choice(np.arange(n*m), len(p))
px, py = x.flatten()[flatten_indices], y.flatten()[flatten_indices]
arr57[px, py] = p
print(arr57)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]] 
 [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 3. 0. 0.]]
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [351]:
arr58 = np.tile(np.arange(3).reshape(1,3), (3,1))
means = arr58.mean(axis=1, keepdims=True)
print(means)
print(arr58)
print(arr58 - means)


[[1.]
 [1.]
 [1.]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [375]:
arr59 = np.random.random((3,3))
print(arr59[:,2])
print(arr59[np.argsort(arr59[:,2])])

[0.71358951 0.42960647 0.21620598]
[[0.47203009 0.92637861 0.21620598]
 [0.27298232 0.35250384 0.42960647]
 [0.68833002 0.59318909 0.71358951]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [381]:
arr60 = np.array([[1,np.nan], [np.nan, np.nan]])
print(np.isnan(arr60).all(axis=0).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [384]:
arr50 = np.random.random(10) * 10 
v = 4
print(arr50)
print(arr50[np.argmin(np.abs(arr50-v))])

[2.48699784 6.88503737 8.75595143 6.11019408 5.62108136 0.45994727
 2.39675691 1.92252179 6.18192866 0.58389669]
2.4869978428418174


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [397]:
import numpy as np

A = np.arange(3, 6).reshape(3, 1) 
B = np.arange(-6, -3).reshape(1, 3) 

it = np.nditer([A, B, None]) 
for x, y, arr62 in it:
    arr62[...] = x + y  

print(it.operands[2])  



[[-3 -2 -1]
 [-2 -1  0]
 [-1  0  1]]


#### 63. Create an array class that has a name attribute (★★☆)

In [399]:
class new_array(np.ndarray):
    def __new__(cls, array, name="-"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        super().__array_finalize__(obj)  
        self.name = getattr(obj, 'name', "-")

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [407]:
A, B = np.array([2, 3, 5, 7, 6]), np.array([0, 4, 2, 2])
print(A)
a, c = np.unique(B, return_counts=True)
A[a] += c
print(A)

[2 3 5 7 6]
[3 3 7 7 7]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [414]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
ans = np.zeros(np.max(I)+1)
np.add.at(ans, I, X)
#answer(65)
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(np.array_equal(ans, F))

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.] [0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]
True


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [427]:
b = np.ones((3,3,3))
reshaped = b.reshape(-1, b.shape[-1])
unique_b = np.unique(reshaped, axis=0)
print(unique_b)

[[1. 1. 1.]]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [430]:
a = np.ones((2,2,2,2))
print(a.sum(axis=(-2, -1)))

[[4. 4.]
 [4. 4.]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [436]:
import numpy as np

arr = np.array([1, 6, 3, 8, 5])
masked_arr = np.ma.masked_where(arr > 5, arr)
mean_value = masked_arr.mean()
print(f"Mean of elements where values are not greater than 5: {mean_value}")

Mean of elements where values are not greater than 5: 3.0


#### 69. How to get the diagonal of a dot product? (★★★)

In [438]:
a,b = np.random.random((5,5)), np.random.random((5,5))
print(np.diag(np.dot(a,b)))

[1.70640702 0.68094315 1.4664158  0.23225932 1.73408995]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [440]:
tmp = np.arange(1,6)
arr70 = np.zeros(len(tmp) * 4)
arr70[np.arange(0,4*len(tmp),4)] = tmp 
print(arr70)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [455]:
tmp1 = np.ones((5,5,3))
tmp2 = 2*np.ones((5,5))
print(tmp1 * tmp2.reshape((5,5,1)))

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [453]:
a = np.tile(np.array([1,2]), (2,1)).T
print(a)
a[[0,1]] = a[[1,0]]
print(a)

[[1 1]
 [2 2]]
[[2 2]
 [1 1]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [478]:
t = np.random.random((10, 3))
paris = ((0,1), (0,2), (1,2))
possible_pairs = np.vstack(tuple(np.hstack((t[:,i].reshape((-1,1)), t[:,j].reshape(-1,1))) for i,j in paris))
possible_pairs.sort(axis=-1)
arr73 = np.unique(possible_pairs, axis=0)
print(arr73.shape)

(30, 2)


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [489]:
np.repeat(np.arange(2), [2,3])
C = np.array([1,2,3])
A = np.repeat(np.arange(len(C)), repeats=C)
print(C, A, np.bincount(A) == C)

[1 2 3] [0 1 1 2 2 2] [ True  True  True]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [495]:
arr75 = np.arange(10)
print(np.lib.stride_tricks.sliding_window_view(arr75, window_shape=3).mean(axis=-1))

[1. 2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [500]:
Z = np.arange(15)
print(np.lib.stride_tricks.sliding_window_view(Z, window_shape=3))

[[ 0  1  2]
 [ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [499]:
arr77 = np.random.random(10)
np.logical_not(arr77, out=arr77)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [620]:
def distance(P0, P1, p):
    x0, y0 = P0[:,0], P0[:,1]
    x2, y2 = P1[:,0], P1[:,1]
    x, y = p[0,0], p[0,1]


    numerator = abs((y2 - y0) * x - (x2 - x0) * y + x2 * y0 - y2 * x0)
    denominator = np.sqrt((y2 - y0)**2 + (x2 - x0)**2)

    return numerator / denominator

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[1.17778787 0.20315351 4.74255001 8.71118325 0.80911207 4.03467184
 4.37627804 1.8607654  2.85592961 2.95807904]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [626]:
answer(79)

# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

# Author: Yang Wu (Broadcasting)
def distance_points_to_lines(p: np.ndarray, p_1: np.ndarray, p_2: np.ndarray) -> np.ndarray:
    x_0, y_0 = p.T  # Shape -> (n points, )
    x_1, y_1 = p_1.T  # Shape -> (n lines, )
    x_2, y_2 = p_2.T  # Shape -> (n lines, )

    # Displacement vector coordinates from p_1 -> p_2
    dx = x_2 - x_1  # Shape -> (n lines, )
    dy = y_2 - y_1  # Shape -> (n lines, )

    # The 'cross product' term
    cross_term = x_2 * y_1 - y_2 * x_1  # Shape -> (n lines, )

    # Broadcast x_0, y_0 (n points, 1) and dx, dy, cross_term (1, n lines) -> (n points, n lines)
    numerator = np.abs(
        dy[np.newaxis, :] * x_0[:, np.newaxis]
        - dx[np.newaxis, :] * y_0[:, np.newaxis]
        + cross_term[np.newaxis, 

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [652]:
n, m = 6, 6 
arr80 = np.ones((n,m))
subgraph_shape = np.array([7,3], dtype=int)
center =  np.array([3,3], dtype=int) 
paded = np.pad(arr80, pad_width=((subgraph_shape[0], subgraph_shape[0]), (subgraph_shape[1], subgraph_shape[1])), mode='constant',)

edited_center = center + subgraph_shape
print(edited_center)
x0, x1 = edited_center[0]-subgraph_shape[0]//2, edited_center[0]+subgraph_shape[0]//2+1
y0, y1 = edited_center[1]-subgraph_shape[1]//2, edited_center[1]+subgraph_shape[1]//2+1
print(paded[x0:x1,y0:y1])

[10  6]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [502]:
Z = np.arange(1, 15, dtype=np.uint32)
print(np.lib.stride_tricks.sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [504]:
arr82 = np.random.random((5,5))
print(np.linalg.matrix_rank(arr82))

5


#### 83. How to find the most frequent value in an array?

In [507]:
arr83 = np.array([1,2,3,2,0])
v, c = np.unique(arr83, return_counts=True)
print(v[c.argmax()])

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [513]:
arr84 = np.arange(100).reshape((10, 10))
print(np.lib.stride_tricks.sliding_window_view(arr84, window_shape=(3,3)).reshape((-1,3,3)).shape)

(64, 3, 3)


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [519]:
arr84 = np.ones(64).reshape((8, 8)).astype(int)
print(np.lib.stride_tricks.sliding_window_view(arr84, window_shape=(4,4)).sum(axis=(-2,-1)))

[[16 16 16 16 16]
 [16 16 16 16 16]
 [16 16 16 16 16]
 [16 16 16 16 16]
 [16 16 16 16 16]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation 

n, m = 100, 100
world = np.random.randint(0, 2, (n, m))

fig, ax = plt.subplots()
image = ax.imshow(world, cmap='gray')

def get_number_of_live_neighbors(world: np.ndarray):
    x_diffs, y_diffs = np.meshgrid(np.arange(-1, 2), np.arange(-1, 2))
    x_diffs, y_diffs = x_diffs.flatten(), y_diffs.flatten()

    shifted_worlds = []
    for xdiff, ydiff in zip(x_diffs, y_diffs):
        shifted_worlds.append(np.roll(np.roll(world, shift=ydiff, axis=0), shift=xdiff, axis=1))
    number_of_live_neighbors = sum(shifted_worlds)
    return number_of_live_neighbors - world

In [ ]:

def init():
    ax.set_xlim(0, m)
    ax.set_ylim(0, n)
    ax.set_axis_off()
    return [image]
    


def next_frame(frame):
    global world 
    number_of_live_neighbors = get_number_of_live_neighbors(world) 
    survive_condition = ((world == 1) & ((2 <= number_of_live_neighbors) & (number_of_live_neighbors <= 3))) 
    birth_condition = ((world == 0) & (number_of_live_neighbors == 3)) 
    new_world = (survive_condition | birth_condition).astype(world.dtype)
    # print(world, '\n', number_of_live_neighbors,'\n', survive_condition,'\n', birth_condition, '\n',new_world)
    world = new_world
    image.set_data(world)
    return [image]

def game_or_life():
    ani = FuncAnimation(fig, next_frame, frames=100, init_func=init, blit=True, interval=200)
    plt.show()


if __name__ == '__main__':
    game_or_life()

#### 89. How to get the n largest values of an array (★★★)

In [522]:
arr89 = np.arange(10)
print(arr89[np.argsort(arr89)[-4:]])

[6 7 8 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [616]:
vs = [np.arange(3), np.arange(3), np.arange(3)]
v_indices = np.meshgrid(*vs)
v_indices = tuple(map(lambda i: i.flatten().reshape((-1,1)), v_indices))
print(np.hstack(v_indices))

[[0 0 0]
 [0 0 1]
 [0 0 2]
 [1 0 0]
 [1 0 1]
 [1 0 2]
 [2 0 0]
 [2 0 1]
 [2 0 2]
 [0 1 0]
 [0 1 1]
 [0 1 2]
 [1 1 0]
 [1 1 1]
 [1 1 2]
 [2 1 0]
 [2 1 1]
 [2 1 2]
 [0 2 0]
 [0 2 1]
 [0 2 2]
 [1 2 0]
 [1 2 1]
 [1 2 2]
 [2 2 0]
 [2 2 1]
 [2 2 2]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
dtype = [('name', 'U10'), ('age', 'i4'), ('height', 'f4')]
arr91 = np.recarray(3, dtype=dtype)
arr91['name'] = ['Alice', 'Bob', 'Charlie']
arr91['age'] = [25, 30, 35]
arr91['height'] = [5.5, 6.0, 5.9]
print(arr91)

[('Alice', 25, 5.5) ('Bob', 30, 6. ) ('Charlie', 35, 5.9)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [527]:
arr92 = np.random.rand(int(1e5))
%timeit np.power(arr92,3)
%timeit arr92*arr92*arr92
%timeit np.einsum('i,i,i->i', arr92, arr92, arr92)

841 μs ± 4.89 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
88.2 μs ± 9.02 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
48.1 μs ± 2.05 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [598]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A)
print()
print(B)
np.logical_not(np.subtract.outer(A, B).all(axis=-1)).any(axis=-2).all(axis=-1)

[[3 3 1]
 [3 2 1]
 [0 2 1]
 [1 2 2]
 [4 3 1]
 [0 4 0]
 [2 0 1]
 [3 1 2]]

[[4 0]
 [0 4]]


array([False, False,  True, False,  True,  True,  True, False])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [533]:
arr94 = np.array([[1,1,1], [1,2,3], [1,2,1]])
maxs = np.max(arr94, axis=-1, keepdims=True)
arr94 -= maxs
print(~arr94.any(axis=-1))

[ True False False]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [558]:
arr95 = np.arange(10, dtype=np.uint8)
print(np.unpackbits(arr95).reshape((-1,8)))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [538]:
arr96 = np.array([[1,1,1], [1,2,3], [1,2,1], [1,1,1]])
v,c = np.unique(arr96, axis=0, return_counts=True)
print(v[c==1])

[[1 2 1]
 [1 2 3]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [565]:
a, b = np.arange(5), np.arange(5)
print(f'a:{a}, b:{b}')
print(f'inner:{np.einsum('i,i->', a, b)}')
print(f'outer:{np.einsum('i,j->ij', a, b)}')
print(f'sum:{np.einsum('i->', a)}')
print(f'mul:{np.einsum('i,i->i', a, b)}')

a:[0 1 2 3 4], b:[0 1 2 3 4]
inner:30
outer:[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]
sum:10
mul:[ 0  1  4  9 16]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)